{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: PyAthena in ./.venv/lib/python3.13/site-packages (3.12.2)\n",
      "Requirement already satisfied: boto3>=1.26.4 in ./.venv/lib/python3.13/site-packages (from PyAthena) (1.37.20)\n",
      "Requirement already satisfied: botocore>=1.29.4 in ./.venv/lib/python3.13/site-packages (from PyAthena) (1.37.20)\n",
      "Requirement already satisfied: fsspec in ./.venv/lib/python3.13/site-packages (from PyAthena) (2025.3.0)\n",
      "Requirement already satisfied: python-dateutil in ./.venv/lib/python3.13/site-packages (from PyAthena) (2.9.0.post0)\n",
      "Requirement already satisfied: tenacity>=4.1.0 in ./.venv/lib/python3.13/site-packages (from PyAthena) (9.0.0)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.venv/lib/python3.13/site-packages (from boto3>=1.26.4->PyAthena) (1.0.1)\n",
      "Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in ./.venv/lib/python3.13/site-packages (from boto3>=1.26.4->PyAthena) (0.11.4)\n",
      "Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in ./.venv/lib/python3.13/site-packages (from botocore>=1.29.4->PyAthena) (2.3.0)\n",
      "Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil->PyAthena) (1.17.0)\n",
      "Requirement already satisfied: numpy in ./.venv/lib/python3.13/site-packages (2.2.4)\n",
      "Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.13/site-packages (from pandas) (2.2.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: datetime in ./.venv/lib/python3.13/site-packages (5.5)\n",
      "Requirement already satisfied: zope.interface in ./.venv/lib/python3.13/site-packages (from datetime) (7.2)\n",
      "Requirement already satisfied: pytz in ./.venv/lib/python3.13/site-packages (from datetime) (2025.2)\n",
      "Requirement already satisfied: setuptools in ./.venv/lib/python3.13/site-packages (from zope.interface->datetime) (78.0.2)\n",
      "Requirement already satisfied: matplotlib in ./.venv/lib/python3.13/site-packages (3.10.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.3.1)\n",
      "Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (4.56.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.4.8)\n",
      "Requirement already satisfied: numpy>=1.23 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.2.4)\n",
      "Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (24.2)\n",
      "Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.13/site-packages (from matplotlib) (11.1.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (3.2.3)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)\n",
      "Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)\n",
      "\u001b[31mERROR: Could not find a version that satisfies the requirement os (from versions: none)\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[31mERROR: No matching distribution found for os\u001b[0m\u001b[31m\n",
      "\u001b[0mRequirement already satisfied: boto3 in ./.venv/lib/python3.13/site-packages (1.37.20)\n",
      "Requirement already satisfied: botocore<1.38.0,>=1.37.20 in ./.venv/lib/python3.13/site-packages (from boto3) (1.37.20)\n",
      "Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.venv/lib/python3.13/site-packages (from boto3) (1.0.1)\n",
      "Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in ./.venv/lib/python3.13/site-packages (from boto3) (0.11.4)\n",
      "Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.venv/lib/python3.13/site-packages (from botocore<1.38.0,>=1.37.20->boto3) (2.9.0.post0)\n",
      "Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in ./.venv/lib/python3.13/site-packages (from botocore<1.38.0,>=1.37.20->boto3) (2.3.0)\n",
      "Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.38.0,>=1.37.20->boto3) (1.17.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install PyAthena\n",
    "!pip install numpy\n",
    "!pip install pandas\n",
    "!pip install datetime\n",
    "!pip install matplotlib\n",
    "!pip install os\n",
    "!pip install boto3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Failed to execute query.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/common.py\", line 586, in _execute\n",
      "    query_id = retry_api_call(\n",
      "               ~~~~~~~~~~~~~~^\n",
      "        self._connection.client.start_query_execution,\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    ...<2 lines>...\n",
      "        **request,\n",
      "        ^^^^^^^^^^\n",
      "    ).get(\"QueryExecutionId\")\n",
      "    ^\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/util.py\", line 84, in retry_api_call\n",
      "    return retry(func, *args, **kwargs)\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py\", line 475, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py\", line 376, in iter\n",
      "    result = action(retry_state)\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py\", line 398, in <lambda>\n",
      "    self._add_action_func(lambda rs: rs.outcome.result())\n",
      "                                     ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py\", line 449, in result\n",
      "    return self.__get_result()\n",
      "           ~~~~~~~~~~~~~~~~~^^\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py\", line 401, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py\", line 478, in __call__\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/client.py\", line 570, in _api_call\n",
      "    return self._make_api_call(operation_name, kwargs)\n",
      "           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/context.py\", line 124, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/pranavigupta/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/client.py\", line 1031, in _make_api_call\n",
      "    raise error_class(parsed_response, operation_name)\n",
      "botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket my-athena-results-bucket\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket my-athena-results-bucket",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mInvalidRequestException\u001b[39m                   Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/common.py:586\u001b[39m, in \u001b[36mBaseCursor._execute\u001b[39m\u001b[34m(self, operation, parameters, work_group, s3_staging_dir, cache_size, cache_expiration_time, result_reuse_enable, result_reuse_minutes, paramstyle)\u001b[39m\n\u001b[32m    585\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m586\u001b[39m     query_id = \u001b[43mretry_api_call\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    587\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_connection\u001b[49m\u001b[43m.\u001b[49m\u001b[43mclient\u001b[49m\u001b[43m.\u001b[49m\u001b[43mstart_query_execution\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    588\u001b[39m \u001b[43m        \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_retry_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    589\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlogger\u001b[49m\u001b[43m=\u001b[49m\u001b[43m_logger\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    590\u001b[39m \u001b[43m        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    591\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m.get(\u001b[33m\"\u001b[39m\u001b[33mQueryExecutionId\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m    592\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/util.py:84\u001b[39m, in \u001b[36mretry_api_call\u001b[39m\u001b[34m(func, config, logger, *args, **kwargs)\u001b[39m\n\u001b[32m     69\u001b[39m retry = tenacity.Retrying(\n\u001b[32m     70\u001b[39m     retry=retry_if_exception(\n\u001b[32m     71\u001b[39m         \u001b[38;5;28;01mlambda\u001b[39;00m e: \u001b[38;5;28mgetattr\u001b[39m(e, \u001b[33m\"\u001b[39m\u001b[33mresponse\u001b[39m\u001b[33m\"\u001b[39m, {}).get(\u001b[33m\"\u001b[39m\u001b[33mError\u001b[39m\u001b[33m\"\u001b[39m, {}).get(\u001b[33m\"\u001b[39m\u001b[33mCode\u001b[39m\u001b[33m\"\u001b[39m) \u001b[38;5;129;01min\u001b[39;00m config.exceptions\n\u001b[32m   (...)\u001b[39m\u001b[32m     82\u001b[39m     reraise=\u001b[38;5;28;01mTrue\u001b[39;00m,\n\u001b[32m     83\u001b[39m )\n\u001b[32m---> \u001b[39m\u001b[32m84\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mretry\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfunc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py:475\u001b[39m, in \u001b[36mRetrying.__call__\u001b[39m\u001b[34m(self, fn, *args, **kwargs)\u001b[39m\n\u001b[32m    474\u001b[39m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m475\u001b[39m     do = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43miter\u001b[49m\u001b[43m(\u001b[49m\u001b[43mretry_state\u001b[49m\u001b[43m=\u001b[49m\u001b[43mretry_state\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    476\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(do, DoAttempt):\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py:376\u001b[39m, in \u001b[36mBaseRetrying.iter\u001b[39m\u001b[34m(self, retry_state)\u001b[39m\n\u001b[32m    375\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m action \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m.iter_state.actions:\n\u001b[32m--> \u001b[39m\u001b[32m376\u001b[39m     result = \u001b[43maction\u001b[49m\u001b[43m(\u001b[49m\u001b[43mretry_state\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    377\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py:398\u001b[39m, in \u001b[36mBaseRetrying._post_retry_check_actions.<locals>.<lambda>\u001b[39m\u001b[34m(rs)\u001b[39m\n\u001b[32m    397\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m (\u001b[38;5;28mself\u001b[39m.iter_state.is_explicit_retry \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m.iter_state.retry_run_result):\n\u001b[32m--> \u001b[39m\u001b[32m398\u001b[39m     \u001b[38;5;28mself\u001b[39m._add_action_func(\u001b[38;5;28;01mlambda\u001b[39;00m rs: \u001b[43mrs\u001b[49m\u001b[43m.\u001b[49m\u001b[43moutcome\u001b[49m\u001b[43m.\u001b[49m\u001b[43mresult\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[32m    399\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py:449\u001b[39m, in \u001b[36mFuture.result\u001b[39m\u001b[34m(self, timeout)\u001b[39m\n\u001b[32m    448\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m._state == FINISHED:\n\u001b[32m--> \u001b[39m\u001b[32m449\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m__get_result\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    451\u001b[39m \u001b[38;5;28mself\u001b[39m._condition.wait(timeout)\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py:401\u001b[39m, in \u001b[36mFuture.__get_result\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    400\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m401\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m._exception\n\u001b[32m    402\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    403\u001b[39m     \u001b[38;5;66;03m# Break a reference cycle with the exception in self._exception\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/tenacity/__init__.py:478\u001b[39m, in \u001b[36mRetrying.__call__\u001b[39m\u001b[34m(self, fn, *args, **kwargs)\u001b[39m\n\u001b[32m    477\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m478\u001b[39m     result = \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    479\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m:  \u001b[38;5;66;03m# noqa: B902\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/client.py:570\u001b[39m, in \u001b[36mClientCreator._create_api_method.<locals>._api_call\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    569\u001b[39m \u001b[38;5;66;03m# The \"self\" in this scope is referring to the BaseClient.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m570\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_make_api_call\u001b[49m\u001b[43m(\u001b[49m\u001b[43moperation_name\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/context.py:124\u001b[39m, in \u001b[36mwith_current_context.<locals>.decorator.<locals>.wrapper\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    123\u001b[39m     hook()\n\u001b[32m--> \u001b[39m\u001b[32m124\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/botocore/client.py:1031\u001b[39m, in \u001b[36mBaseClient._make_api_call\u001b[39m\u001b[34m(self, operation_name, api_params)\u001b[39m\n\u001b[32m   1030\u001b[39m     error_class = \u001b[38;5;28mself\u001b[39m.exceptions.from_code(error_code)\n\u001b[32m-> \u001b[39m\u001b[32m1031\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m error_class(parsed_response, operation_name)\n\u001b[32m   1032\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "\u001b[31mInvalidRequestException\u001b[39m: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket my-athena-results-bucket",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mDatabaseError\u001b[39m                             Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[50]\u001b[39m\u001b[32m, line 38\u001b[39m\n\u001b[32m     33\u001b[39m conn = connect(region_name=\u001b[33m\"\u001b[39m\u001b[33mus-east-1\u001b[39m\u001b[33m\"\u001b[39m,\n\u001b[32m     34\u001b[39m                s3_staging_dir=\u001b[33m\"\u001b[39m\u001b[33ms3://my-athena-results-bucket/\u001b[39m\u001b[33m\"\u001b[39m,\n\u001b[32m     35\u001b[39m                schema_name=\u001b[33m\"\u001b[39m\u001b[33myour_database_name\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m     37\u001b[39m cursor = conn.cursor()\n\u001b[32m---> \u001b[39m\u001b[32m38\u001b[39m \u001b[43mcursor\u001b[49m\u001b[43m.\u001b[49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mSELECT * FROM your_table LIMIT 10\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m     40\u001b[39m \u001b[38;5;66;03m# The Glue database name of your MIMIC-III parquet data\u001b[39;00m\n\u001b[32m     41\u001b[39m gluedatabase=\u001b[33m\"\u001b[39m\u001b[33mmimiciii\u001b[39m\u001b[33m\"\u001b[39m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/cursor.py:89\u001b[39m, in \u001b[36mCursor.execute\u001b[39m\u001b[34m(self, operation, parameters, work_group, s3_staging_dir, cache_size, cache_expiration_time, result_reuse_enable, result_reuse_minutes, paramstyle, **kwargs)\u001b[39m\n\u001b[32m     75\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mexecute\u001b[39m(\n\u001b[32m     76\u001b[39m     \u001b[38;5;28mself\u001b[39m,\n\u001b[32m     77\u001b[39m     operation: \u001b[38;5;28mstr\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m     86\u001b[39m     **kwargs,\n\u001b[32m     87\u001b[39m ) -> Cursor:\n\u001b[32m     88\u001b[39m     \u001b[38;5;28mself\u001b[39m._reset_state()\n\u001b[32m---> \u001b[39m\u001b[32m89\u001b[39m     \u001b[38;5;28mself\u001b[39m.query_id = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_execute\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m     90\u001b[39m \u001b[43m        \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     91\u001b[39m \u001b[43m        \u001b[49m\u001b[43mparameters\u001b[49m\u001b[43m=\u001b[49m\u001b[43mparameters\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     92\u001b[39m \u001b[43m        \u001b[49m\u001b[43mwork_group\u001b[49m\u001b[43m=\u001b[49m\u001b[43mwork_group\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     93\u001b[39m \u001b[43m        \u001b[49m\u001b[43ms3_staging_dir\u001b[49m\u001b[43m=\u001b[49m\u001b[43ms3_staging_dir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     94\u001b[39m \u001b[43m        \u001b[49m\u001b[43mcache_size\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcache_size\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     95\u001b[39m \u001b[43m        \u001b[49m\u001b[43mcache_expiration_time\u001b[49m\u001b[43m=\u001b[49m\u001b[43mcache_expiration_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     96\u001b[39m \u001b[43m        \u001b[49m\u001b[43mresult_reuse_enable\u001b[49m\u001b[43m=\u001b[49m\u001b[43mresult_reuse_enable\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     97\u001b[39m \u001b[43m        \u001b[49m\u001b[43mresult_reuse_minutes\u001b[49m\u001b[43m=\u001b[49m\u001b[43mresult_reuse_minutes\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     98\u001b[39m \u001b[43m        \u001b[49m\u001b[43mparamstyle\u001b[49m\u001b[43m=\u001b[49m\u001b[43mparamstyle\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     99\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    100\u001b[39m     query_execution = cast(AthenaQueryExecution, \u001b[38;5;28mself\u001b[39m._poll(\u001b[38;5;28mself\u001b[39m.query_id))\n\u001b[32m    101\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m query_execution.state == AthenaQueryExecution.STATE_SUCCEEDED:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/common.py:594\u001b[39m, in \u001b[36mBaseCursor._execute\u001b[39m\u001b[34m(self, operation, parameters, work_group, s3_staging_dir, cache_size, cache_expiration_time, result_reuse_enable, result_reuse_minutes, paramstyle)\u001b[39m\n\u001b[32m    592\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    593\u001b[39m         _logger.exception(\u001b[33m\"\u001b[39m\u001b[33mFailed to execute query.\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m--> \u001b[39m\u001b[32m594\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m DatabaseError(*e.args) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01me\u001b[39;00m\n\u001b[32m    595\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m query_id\n",
      "\u001b[31mDatabaseError\u001b[39m: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: Unable to verify/create output bucket my-athena-results-bucket"
     ]
    }
   ],
   "source": [
    "from pyathena import connect\n",
    "# from pyathena.util import as_pandas\n",
    "from __future__ import print_function\n",
    "\n",
    "# Import libraries\n",
    "import datetime\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "import boto3\n",
    "from botocore.client import ClientError\n",
    "# below is used to print out pretty pandas dataframes\n",
    "from IPython.display import display, HTML\n",
    "%matplotlib inline\n",
    "\n",
    "\n",
    "s3 = boto3.resource('s3', region_name='us-east-1')\n",
    "client = boto3.client(\"sts\")\n",
    "account_id = client.get_caller_identity()[\"Account\"]\n",
    "my_session = boto3.session.Session()\n",
    "region = my_session.region_name\n",
    "athena_query_results_bucket = 'my-athena-results-bucket-12343434234234324234234234'\n",
    "\n",
    "try:\n",
    "    s3.meta.client.head_bucket(Bucket=athena_query_results_bucket)\n",
    "except ClientError:\n",
    "    bucket = s3.create_bucket(Bucket=athena_query_results_bucket)\n",
    "    print('Creating bucket '+athena_query_results_bucket)\n",
    "cursor = connect(s3_staging_dir='s3://'+athena_query_results_bucket).cursor()\n",
    "\n",
    "\n",
    "conn = connect(region_name=\"us-east-1\",\n",
    "               s3_staging_dir=\"s3://my-athena-results-bucket/\",\n",
    "               schema_name=\"your_database_name\")\n",
    "\n",
    "cursor = conn.cursor()\n",
    "cursor.execute(\"SELECT * FROM your_table LIMIT 10\")\n",
    "\n",
    "# The Glue database name of your MIMIC-III parquet data\n",
    "gluedatabase=\"mimiciii\"\n",
    "\n",
    "# location of the queries to generate aline specific materialized views\n",
    "aline_path = './'\n",
    "\n",
    "# location of the queries to generate materialized views from the MIMIC code repository\n",
    "concepts_path = './concepts/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Bucket my-athena-results-bucket-12343434234234324234234234 already exists.\n",
      "Available tables in mimiciii database: [('admissions',), ('callout',), ('caregivers',), ('chartevents',), ('cptevents',), ('d_cpt',), ('d_icd_diagnoses',), ('d_icd_procedures',), ('d_items',), ('d_labitems',), ('datetimeevents',), ('diagnoses_icd',), ('drgcodes',), ('icustays',), ('inputevents_cv',), ('inputevents_mv',), ('labevents',), ('microbiologyevents',), ('noteevents',), ('outputevents',), ('patients',), ('prescriptions',), ('procedureevents_mv',), ('procedures_icd',), ('services',), ('transfers',)]\n",
      "Error occurred: An error occurred (AccessDenied) when calling the GetObjectAcl operation: Access Denied\n"
     ]
    },
    {
     "ename": "OperationalError",
     "evalue": "com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 5T1GZWVWCHYYBQCW; S3 Extended Request ID: VbRlRTrtDpi9t4oebhwkPJQ/66bN5QyABndq2STyiOGZz5l6eMCng6N/feKPoJvPbwqEY38EgEf+WcLc0N5Kig==; Proxy: null), S3 Extended Request ID: VbRlRTrtDpi9t4oebhwkPJQ/66bN5QyABndq2STyiOGZz5l6eMCng6N/feKPoJvPbwqEY38EgEf+WcLc0N5Kig== (Bucket: mimic-iii-physionet, Key: parquet/PATIENTS/)",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mOperationalError\u001b[39m                          Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[45]\u001b[39m\u001b[32m, line 50\u001b[39m\n\u001b[32m     44\u001b[39m     \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mError occurred: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00me\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m     48\u001b[39m \u001b[38;5;66;03m# Example: Selecting data from the 'PROCEDURES_ICD' table\u001b[39;00m\n\u001b[32m     49\u001b[39m \u001b[38;5;66;03m# You can replace 'PROCEDURES_ICD' with any table name from the list you retrieved\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m50\u001b[39m \u001b[43mcursor\u001b[49m\u001b[43m.\u001b[49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mSELECT * FROM patients LIMIT 10\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m     52\u001b[39m \u001b[38;5;66;03m# Fetch and print results\u001b[39;00m\n\u001b[32m     53\u001b[39m results = cursor.fetchall()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/pyathena/cursor.py:110\u001b[39m, in \u001b[36mCursor.execute\u001b[39m\u001b[34m(self, operation, parameters, work_group, s3_staging_dir, cache_size, cache_expiration_time, result_reuse_enable, result_reuse_minutes, paramstyle, **kwargs)\u001b[39m\n\u001b[32m    102\u001b[39m     \u001b[38;5;28mself\u001b[39m.result_set = \u001b[38;5;28mself\u001b[39m._result_set_class(\n\u001b[32m    103\u001b[39m         \u001b[38;5;28mself\u001b[39m._connection,\n\u001b[32m    104\u001b[39m         \u001b[38;5;28mself\u001b[39m._converter,\n\u001b[32m   (...)\u001b[39m\u001b[32m    107\u001b[39m         \u001b[38;5;28mself\u001b[39m._retry_config,\n\u001b[32m    108\u001b[39m     )\n\u001b[32m    109\u001b[39m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m110\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m OperationalError(query_execution.state_change_reason)\n\u001b[32m    111\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\n",
      "\u001b[31mOperationalError\u001b[39m: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 5T1GZWVWCHYYBQCW; S3 Extended Request ID: VbRlRTrtDpi9t4oebhwkPJQ/66bN5QyABndq2STyiOGZz5l6eMCng6N/feKPoJvPbwqEY38EgEf+WcLc0N5Kig==; Proxy: null), S3 Extended Request ID: VbRlRTrtDpi9t4oebhwkPJQ/66bN5QyABndq2STyiOGZz5l6eMCng6N/feKPoJvPbwqEY38EgEf+WcLc0N5Kig== (Bucket: mimic-iii-physionet, Key: parquet/PATIENTS/)"
     ]
    }
   ],
   "source": [
    "import boto3\n",
    "from botocore.exceptions import ClientError\n",
    "from pyathena import connect\n",
    "import os\n",
    "\n",
    "# Initialize boto3 clients and session\n",
    "s3 = boto3.resource('s3', region_name='us-east-1')\n",
    "client = boto3.client(\"sts\")\n",
    "account_id = client.get_caller_identity()[\"Account\"]\n",
    "my_session = boto3.session.Session()\n",
    "region = my_session.region_name\n",
    "\n",
    "# Define your Athena results bucket\n",
    "athena_query_results_bucket = 'my-athena-results-bucket-12343434234234324234234234'\n",
    "\n",
    "# Check if the bucket exists, and create it if not\n",
    "try:\n",
    "    s3.meta.client.head_bucket(Bucket=athena_query_results_bucket)\n",
    "    print(f\"Bucket {athena_query_results_bucket} already exists.\")\n",
    "except ClientError:\n",
    "    print(f\"Bucket {athena_query_results_bucket} does not exist. Creating it now.\")\n",
    "    s3.create_bucket(Bucket=athena_query_results_bucket, CreateBucketConfiguration={\n",
    "        'LocationConstraint': 'us-east-1'  # Ensure the region is set correctly\n",
    "    })\n",
    "\n",
    "# Connect to Athena and specify the S3 staging directory\n",
    "conn = connect(region_name=\"us-east-1\",\n",
    "               s3_staging_dir=f\"s3://{athena_query_results_bucket}\",\n",
    "               schema_name=\"mimiciii\")  # Use the 'mimiciii' database directly\n",
    "\n",
    "# Create cursor\n",
    "cursor = conn.cursor()\n",
    "\n",
    "# Execute query to list the available tables in the 'mimiciii' database\n",
    "cursor.execute(\"SHOW TABLES\")\n",
    "tables = cursor.fetchall()\n",
    "print(\"Available tables in mimiciii database:\", tables) \n",
    "\n",
    "try:\n",
    "    # Attempt to retrieve the ACL of an object\n",
    "    acl = s3.ObjectAcl('mimic-iii-physionet', 'parquet/PATIENTS/')\n",
    "    print(acl.grants)\n",
    "except Exception as e:\n",
    "    print(f\"Error occurred: {e}\")\n",
    "\n",
    "\n",
    "\n",
    "# Example: Selecting data from the 'PROCEDURES_ICD' table\n",
    "# You can replace 'PROCEDURES_ICD' with any table name from the list you retrieved\n",
    "cursor.execute(\"SELECT * FROM patients LIMIT 10\")\n",
    "\n",
    "# Fetch and print results\n",
    "results = cursor.fetchall()\n",
    "print(\"Results from PATIENTS:\", results)\n",
    "\n",
    "# # Define paths for materialized views queries\n",
    "# aline_path = './'\n",
    "# concepts_path = './concepts/'\n",
    "\n",
    "# # Execute queries from the specified directories for materialized views\n",
    "# def execute_query_from_file(query_path):\n",
    "#     with open(query_path, 'r') as file:\n",
    "#         query = file.read\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: './concepts/sepsis/angus-awsathena.sql'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mFileNotFoundError\u001b[39m                         Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[37]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      3\u001b[39m cursor.execute(query.replace(\u001b[33m\"\u001b[39m\u001b[33mDATABASE\u001b[39m\u001b[33m\"\u001b[39m, gluedatabase))\n\u001b[32m      4\u001b[39m f = os.path.join(concepts_path,\u001b[33m'\u001b[39m\u001b[33msepsis/angus-awsathena.sql\u001b[39m\u001b[33m'\u001b[39m)\n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mf\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m fp:\n\u001b[32m      6\u001b[39m     query = \u001b[33m'\u001b[39m\u001b[33m'\u001b[39m.join(fp.readlines())\n\u001b[32m      8\u001b[39m \u001b[38;5;66;03m# Execute the query\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/data_to_decisions/prevention-data/.venv/lib/python3.13/site-packages/IPython/core/interactiveshell.py:325\u001b[39m, in \u001b[36m_modified_open\u001b[39m\u001b[34m(file, *args, **kwargs)\u001b[39m\n\u001b[32m    318\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m {\u001b[32m0\u001b[39m, \u001b[32m1\u001b[39m, \u001b[32m2\u001b[39m}:\n\u001b[32m    319\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m    320\u001b[39m         \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mIPython won\u001b[39m\u001b[33m'\u001b[39m\u001b[33mt let you open fd=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m by default \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    321\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mas it is likely to crash IPython. If you know what you are doing, \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    322\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33myou can use builtins\u001b[39m\u001b[33m'\u001b[39m\u001b[33m open.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    323\u001b[39m     )\n\u001b[32m--> \u001b[39m\u001b[32m325\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mio_open\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[31mFileNotFoundError\u001b[39m: [Errno 2] No such file or directory: './concepts/sepsis/angus-awsathena.sql'"
     ]
    }
   ],
   "source": [
    "# Load in the query from file\n",
    "query='DROP TABLE IF EXISTS DATABASE.angus_sepsis;'\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "f = os.path.join(concepts_path,'sepsis/angus-awsathena.sql')\n",
    "with open(f) as fp:\n",
    "    query = ''.join(fp.readlines())\n",
    "    \n",
    "# Execute the query\n",
    "print('Generating table \\'angus_sepsis\\' using {} ...'.format(f),end=' ')\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "print('done.')\n",
    "\n",
    "# Load in the query from file\n",
    "query='DROP TABLE IF EXISTS DATABASE.heightweight;'\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "f = os.path.join(concepts_path,'demographics/HeightWeightQuery-awsathena.sql')\n",
    "with open(f) as fp:\n",
    "    query = ''.join(fp.readlines())\n",
    "    \n",
    "# Execute the query\n",
    "print('Generating table \\'heightweight\\' using {} ...'.format(f),end=' ')\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "print('done.')\n",
    "\n",
    "\n",
    "# Load in the query from file\n",
    "query='DROP TABLE IF EXISTS DATABASE.aline_vaso_flag;'\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "f = os.path.join(aline_path,'aline_vaso_flag-awsathena.sql')\n",
    "with open(f) as fp:\n",
    "    query = ''.join(fp.readlines())\n",
    "    \n",
    "# Execute the query\n",
    "print('Generating table \\'aline_vaso_flag\\' using {} ...'.format(f),end=' ')\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "print('done.')\n",
    "\n",
    "\n",
    "# Load in the query from file\n",
    "query='DROP TABLE IF EXISTS DATABASE.ventsettings;'\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "f = os.path.join(concepts_path,'durations/ventilation-settings-awsathena.sql')\n",
    "with open(f) as fp:\n",
    "    query = ''.join(fp.readlines())\n",
    "    \n",
    "# Execute the query\n",
    "print('Generating table \\'vent_settings\\' using {} ...'.format(f),end=' ')\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "print('done.')\n",
    "\n",
    "\n",
    "# Load in the query from file\n",
    "query='DROP TABLE IF EXISTS DATABASE.ventdurations;'\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "f = os.path.join(concepts_path,'durations/ventilation-durations-awsathena.sql')\n",
    "with open(f) as fp:\n",
    "    query = ''.join(fp.readlines())\n",
    "    \n",
    "# Execute the query\n",
    "print('Generating table \\'vent_durations\\' using {} ...'.format(f),end=' ')\n",
    "cursor.execute(query.replace(\"DATABASE\", gluedatabase))\n",
    "print('done.')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
